### ISSUE TITLE
[delete-closed-pr-docs] Fix errors on forks

### ISSUE THREAD

**Issue by kenji-miyake** [autowarefoundation/autoware-github-actions#79]
https://github.com/kenji-miyake/autoware.universe/runs/5189322226?check_suite_focus=true

**Comment by KeisukeShima** [comment]
## Problem
delete-closed-pr fails on forks.

## Reason
In fork repository, the URL is the PR of the fork, but the actual PR exists upstream, so the `curl` command causes an error.
https://github.com/autowarefoundation/autoware-github-actions/blob/61aae66cb37a671d0255eff2196710c4acab834c/delete-closed-pr-docs/action.yaml#L43

## Expected behavior
Delete document directory such as `pr-45, pr-46, etc` in the fork repository.

## Possible solution
- Fix the URL to upstream repository.
- Use pre-condition to prevent runnning this workflow on forks (https://github.com/autowarefoundation/autoware.universe/pull/320)

I think No.1 is a good choice. Because the document directory created on the fork repository should also be deleted.

**Comment by kenji-miyake** [comment]
> Fix the URL to upstream repository.

I'm sorry, I couldn't understand this. Could you explain it a bit more in detail?
I think the problem is that some directories in `gh-pages` are copied when forked.

**Comment by kenji-miyake** [comment]
I believe we can fix this action to remove a mike version if there is no corresponding PR.

**Comment by KeisukeShima** [comment]
> I think the problem is that some directories in gh-pages are copied when forked.

I would like to confirm, the `pr` directory in the following branch was not created by you?
https://github.com/kenji-miyake/autoware.universe/tree/gh-pages

**Comment by kenji-miyake** [comment]
@KeisukeShima No, they are just copied.

**Comment by kenji-miyake** [comment]
It seems we have to remove the `-f` option?

**Comment by KeisukeShima** [comment]
@kenji-miyake 
> @KeisukeShima No, they are just copied.

I see. I misunderstood.

So, the expected behavior is that simply skip `pr-[number]` directory when there are no corresponding PR on fork repository, right?

And your suggested solution is to remove the `curl -f` option. Because it will suppress the 404 error.

**Comment by kenji-miyake** [comment]
> So, the expected behavior is that simply skip pr-[number] directory when there are no corresponding PR on fork repository, right?

Hmm, I think we can remove the version.

> And your suggested solution is to remove the curl -f option. Because it will suppress the 404 error.

Yes. Like this?

```bash
response=$(curl -sSL "$url" -H "Authorization: token ${{ inputs.token }}")
message=$(echo "$response" | grep -oP '"message": "\K([^"]+)')
state=$(echo "$response" | grep -oP '"state": "\K([a-z]+)')

if [ "$message" = "Not Found" ] || [ "$state" = "closed" ]; then
  closed_docs_versions+=("$docs_version")
fi
```

**Comment by KeisukeShima** [comment]
Created PR #112

**Comment by kenji-miyake** [comment]
@KeisukeShima Hmm, it seems there is another error... :thinking: 
https://github.com/kenji-miyake/autoware.universe/runs/5638055818?check_suite_focus=true#step:3:135

**Comment by kenji-miyake** [comment]
We need "|| true"?

**Comment by kenji-miyake** [comment]
@KeisukeShima Could you confirm and test this, please? :pray:

**Comment by kenji-miyake** [comment]
@KeisukeShima Passed! Thank you. :pray: 
https://github.com/kenji-miyake/autoware.universe/runs/5639262045?check_suite_focus=true
